### PR TITLE
Applied Semantic UI for problem set edit page

### PR DESCRIPTION
**Pull request by mman39**
Applied basic Semantic UI elements and modified testings properly

### CODE REVIEW

**Review by TLB-MISS — APPROVED** [review]

**Comment by TLB-MISS** [comment]
Approved for speedy progress. However, if you can afford it, I would appreciate it if you could solve the solvler key error of the backend.

**Comment by mman39** [comment]
I'll check and update PR if I fix it.

**Comment by mman39** [comment]
And I found a test for creating new problem set in problem set action is not updated yet.

**Review by Zagoshipda — APPROVED** [review]
@mman39 I forgot to do that. Thanks for reminding me and I'll update it.

**Pull request merged**
