### PR TITLE
feat: Implement back-end for UserProfile

### PR DESCRIPTION
**Pull request by clarkindy**
I have used class-based view for UserProfile. I think that should resolve [SonarCloud complaining about mixing safe and unsafe HTTP methods](https://sonarcloud.io/project/security_hotspots?id=swsnu_swpp2021-team13) (See also swsnu/swppfall2021#138). We will find that out after this PR is merged into our branch.

### CODE REVIEW

**Comment by TLB-MISS** [comment]
In my opinion, the travis CI error shown in the attached photo below should be resolved first.
By the way, why did the ability to approve disappear?
image

**Comment by clarkindy** [comment]
> In my opinion, the travis CI error shown in the attached photo below should be resolved first.
I will check it out.

> why did the ability to approve disappear?
You can add an empty approving review in "Files changed" tab of the pull request.

**Comment by TLB-MISS** [comment]
> You can add an empty approving review in "Files changed" tab of the pull request.
Oh, I forgot that. thank you.

**Comment by clarkindy** [comment]
I fixed the build. I explained the cause of the CI error in the commit message.
@Zagoshipda, I only fixed the CI error, so you might want to fix your test cases in `ProfileStatistics.test.tsx`.

**Review by TLB-MISS — APPROVED** [review]
LGTM. I think this should be merged quickly.

**Review by mman39 — APPROVED** [review]

**Pull request merged**
